<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DefaultMediaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('media')->delete();
        
        \DB::table('media')->insert(array (
            0 => 
            array (
                'id' => 11,
                'model_type' => 'App\\Models\\Social_auth',
                'model_id' => 4,
                'uuid' => '72f0405a-1916-4192-822a-f79a3223f985',
                'collection_name' => 'social_auth_picture',
                'name' => 'AOh14GjTPHdvJdWwCwURfRbD1yxE5hL1VMFBOBnyYO_nPA=s96-c',
                'file_name' => 'AOh14GjTPHdvJdWwCwURfRbD1yxE5hL1VMFBOBnyYO_nPA=s96-c.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 4580,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 8,
                'created_at' => '2021-02-23 10:05:12',
                'updated_at' => '2021-02-23 10:05:12',
            ),
            1 => 
            array (
                'id' => 12,
                'model_type' => 'App\\Models\\Blog_post',
                'model_id' => 1,
                'uuid' => '83b65bef-7b69-4a6a-8a63-bf8a9010cadc',
                'collection_name' => 'post_picture',
                'name' => 'umbrella_colorful_positive_138246_3840x2160',
                'file_name' => 'umbrella_colorful_positive_138246_3840x2160.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 1385887,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 9,
                'created_at' => '2021-02-23 10:09:12',
                'updated_at' => '2021-02-23 10:09:12',
            ),
            2 => 
            array (
                'id' => 13,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 1,
                'uuid' => '0feb10dd-7bd8-415f-9c35-95b21f8edaad',
                'collection_name' => 'galleryPictureItems',
                'name' => 'xps-7ZWVnVSaafY-unsplash',
                'file_name' => 'xps-7ZWVnVSaafY-unsplash.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 976106,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Wallpaper","description":""}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 10,
                'created_at' => '2021-02-23 10:20:32',
                'updated_at' => '2021-02-23 10:20:32',
            ),
            3 => 
            array (
                'id' => 14,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 1,
                'uuid' => '6d30901b-0896-49a0-9605-8c604dfcdd5e',
                'collection_name' => 'galleryPictureItems',
                'name' => 'safar-safarov-LKsHwgzyk7c-unsplash',
                'file_name' => 'safar-safarov-LKsHwgzyk7c-unsplash.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 671307,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Wallpaper","description":""}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 11,
                'created_at' => '2021-02-23 10:20:32',
                'updated_at' => '2021-02-23 10:20:32',
            ),
            4 => 
            array (
                'id' => 15,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 1,
                'uuid' => '725d6b38-72a3-47f0-9709-70ddc86ce3a1',
                'collection_name' => 'galleryPictureItems',
                'name' => 'pexels-rodrigo-souza-2531709',
                'file_name' => 'pexels-rodrigo-souza-2531709.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 806079,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Wallpaper","description":""}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 12,
                'created_at' => '2021-02-23 10:20:32',
                'updated_at' => '2021-02-23 10:20:32',
            ),
            5 => 
            array (
                'id' => 16,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 1,
                'uuid' => 'f401f4f6-842d-4917-9982-78d094bc6de9',
                'collection_name' => 'galleryPictureItems',
                'name' => 'pexels-pixabay-36039',
                'file_name' => 'pexels-pixabay-36039.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 718248,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Wallpaper","description":""}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 13,
                'created_at' => '2021-02-23 10:20:32',
                'updated_at' => '2021-02-23 10:20:32',
            ),
            6 => 
            array (
                'id' => 17,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 1,
                'uuid' => '2f84fa85-b885-4abd-86cc-8eb84c088302',
                'collection_name' => 'galleryPictureItems',
                'name' => 'umbrella_colorful_positive_138246_3840x2160',
                'file_name' => 'umbrella_colorful_positive_138246_3840x2160.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 1385887,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Wallpaper","description":""}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 14,
                'created_at' => '2021-02-23 10:20:33',
                'updated_at' => '2021-02-23 10:20:33',
            ),
            7 => 
            array (
                'id' => 18,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 1,
                'uuid' => '26cb5c2a-c31f-4497-82a8-aed890a7df9c',
                'collection_name' => 'galleryPictureItems',
                'name' => 'pexels-pixabay-265987',
                'file_name' => 'pexels-pixabay-265987.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 1355444,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Wallpaper","description":""}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 15,
                'created_at' => '2021-02-23 10:20:33',
                'updated_at' => '2021-02-23 10:20:33',
            ),
            8 => 
            array (
                'id' => 19,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 1,
                'uuid' => 'a261af93-6497-4d51-86c8-72834067a635',
                'collection_name' => 'galleryPictureItems',
                'name' => 'pexels-vincent-gerbouin-1174732',
                'file_name' => 'pexels-vincent-gerbouin-1174732.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 1393929,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Wallpaper","description":""}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 16,
                'created_at' => '2021-02-23 10:20:33',
                'updated_at' => '2021-02-23 10:20:33',
            ),
            9 => 
            array (
                'id' => 20,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 1,
                'uuid' => '392a3e4b-78d7-493e-845a-d31facf4b04d',
                'collection_name' => 'galleryPictureItems',
                'name' => 'pexels-khairul-onggon-908055',
                'file_name' => 'pexels-khairul-onggon-908055.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 773455,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Wallpaper","description":""}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 17,
                'created_at' => '2021-02-23 10:20:33',
                'updated_at' => '2021-02-23 10:20:33',
            ),
            10 => 
            array (
                'id' => 21,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 1,
                'uuid' => '8a03531c-7a29-43b4-9947-5e873c25f2e7',
                'collection_name' => 'galleryPictureItems',
                'name' => 'pexels-pavlo-luchkovski-337901',
                'file_name' => 'pexels-pavlo-luchkovski-337901.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 1452765,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Wallpaper","description":""}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 18,
                'created_at' => '2021-02-23 10:20:33',
                'updated_at' => '2021-02-23 10:20:33',
            ),
            11 => 
            array (
                'id' => 22,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 4,
                'uuid' => '569bee8b-dbcf-4eaa-9842-990720a441bf',
                'collection_name' => 'logo',
                'name' => 'unnamed',
                'file_name' => 'unnamed.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 232526,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 19,
                'created_at' => '2021-02-24 02:40:59',
                'updated_at' => '2021-02-24 02:40:59',
            ),
            12 => 
            array (
                'id' => 23,
                'model_type' => 'App\\Models\\Division',
                'model_id' => 1,
                'uuid' => 'e2700eb1-dd4e-40b2-af97-dc6904178ff2',
                'collection_name' => 'divisionPicture',
                'name' => 'Kerohanian',
                'file_name' => 'Kerohanian.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 7908,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 20,
                'created_at' => '2021-02-24 02:41:52',
                'updated_at' => '2021-02-24 02:41:52',
            ),
            13 => 
            array (
                'id' => 24,
                'model_type' => 'App\\Models\\Division',
                'model_id' => 2,
                'uuid' => '09f82721-21a7-4222-bcfa-2e5c1ec1039b',
                'collection_name' => 'divisionPicture',
                'name' => 'KWU',
                'file_name' => 'KWU.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 6167,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 21,
                'created_at' => '2021-02-24 02:42:00',
                'updated_at' => '2021-02-24 02:42:00',
            ),
            14 => 
            array (
                'id' => 25,
                'model_type' => 'App\\Models\\Division',
                'model_id' => 3,
                'uuid' => '84a1ae90-0f70-43e9-8089-da818d31fea3',
                'collection_name' => 'divisionPicture',
                'name' => 'Minbak',
                'file_name' => 'Minbak.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 10366,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 22,
                'created_at' => '2021-02-24 02:42:07',
                'updated_at' => '2021-02-24 02:42:07',
            ),
            15 => 
            array (
                'id' => 26,
                'model_type' => 'App\\Models\\Division',
                'model_id' => 4,
                'uuid' => '6c741ad5-9f5b-4b0a-a59c-7599f859b1b6',
                'collection_name' => 'divisionPicture',
                'name' => 'IT',
                'file_name' => 'IT.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 5525,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 23,
                'created_at' => '2021-02-24 02:42:15',
                'updated_at' => '2021-02-24 02:42:15',
            ),
            16 => 
            array (
                'id' => 27,
                'model_type' => 'App\\Models\\Division',
                'model_id' => 5,
                'uuid' => 'b5ee9f63-84bb-41ba-ada7-893f89057382',
                'collection_name' => 'divisionPicture',
                'name' => 'Pengabdian Masyarakat',
                'file_name' => 'Pengabdian-Masyarakat.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 10350,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 24,
                'created_at' => '2021-02-24 02:42:20',
                'updated_at' => '2021-02-24 02:42:20',
            ),
            17 => 
            array (
                'id' => 28,
                'model_type' => 'App\\Models\\Division',
                'model_id' => 6,
                'uuid' => 'b3e0baa6-ece8-43db-8a12-06b2a9b4fb0a',
                'collection_name' => 'divisionPicture',
                'name' => 'PSDM',
                'file_name' => 'PSDM.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 6873,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 25,
                'created_at' => '2021-02-24 02:42:26',
                'updated_at' => '2021-02-24 02:42:26',
            ),
            18 => 
            array (
                'id' => 29,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 2,
                'uuid' => '9f9aa34e-57eb-4346-984c-d7a280d29df8',
                'collection_name' => 'galleryPictureItems',
                'name' => 'himatif-white',
                'file_name' => 'himatif-white.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 4994,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Himatif Test","description":"Lorem ipsum dolor sit amet consectetur"}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 26,
                'created_at' => '2021-02-27 01:51:48',
                'updated_at' => '2021-02-27 01:51:48',
            ),
            19 => 
            array (
                'id' => 30,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 2,
                'uuid' => '86f8d8c9-52dc-44ef-81fe-da6626f2dbde',
                'collection_name' => 'galleryPictureItems',
                'name' => 'brand-logo',
                'file_name' => 'brand-logo.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 5383,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Himatif Test","description":"Lorem ipsum dolor sit amet consectetur"}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 26,
                'created_at' => '2021-02-27 01:51:48',
                'updated_at' => '2021-02-27 01:51:48',
            ),
            20 => 
            array (
                'id' => 31,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 2,
                'uuid' => '2a67e1d7-ade4-4018-87df-258635fce17b',
                'collection_name' => 'galleryPictureItems',
                'name' => 'PSDM',
                'file_name' => 'PSDM.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 6873,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Himatif Test","description":"Lorem ipsum dolor sit amet consectetur"}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 27,
                'created_at' => '2021-02-27 01:51:48',
                'updated_at' => '2021-02-27 01:51:48',
            ),
            21 => 
            array (
                'id' => 32,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 2,
                'uuid' => 'bac63c50-d88b-4540-94eb-ad480cb448e1',
                'collection_name' => 'galleryPictureItems',
                'name' => 'Pengabdian Masyarakat',
                'file_name' => 'Pengabdian-Masyarakat.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 10350,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Himatif Test","description":"Lorem ipsum dolor sit amet consectetur"}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 27,
                'created_at' => '2021-02-27 01:51:48',
                'updated_at' => '2021-02-27 01:51:48',
            ),
            22 => 
            array (
                'id' => 33,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 2,
                'uuid' => 'ca28832a-68c9-4418-90cf-12714421240d',
                'collection_name' => 'galleryPictureItems',
                'name' => 'bg-article',
                'file_name' => 'bg-article.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 960021,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Himatif Test","description":"Lorem ipsum dolor sit amet consectetur"}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 28,
                'created_at' => '2021-02-27 01:51:48',
                'updated_at' => '2021-02-27 01:51:48',
            ),
            23 => 
            array (
                'id' => 34,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 2,
                'uuid' => 'a9089488-63ec-4bba-babe-4d5ee15160a9',
                'collection_name' => 'galleryPictureItems',
                'name' => 'notip',
                'file_name' => 'notip.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 53620,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Himatif Test","description":"Lorem ipsum dolor sit amet consectetur"}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 28,
                'created_at' => '2021-02-27 01:51:48',
                'updated_at' => '2021-02-27 01:51:48',
            ),
            24 => 
            array (
                'id' => 35,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 2,
                'uuid' => '4d25abe7-9c6a-4a75-98f1-31f5707104ec',
                'collection_name' => 'galleryPictureItems',
                'name' => 'user-default',
                'file_name' => 'user-default.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 12515,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Himatif Test","description":"Lorem ipsum dolor sit amet consectetur"}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 27,
                'created_at' => '2021-02-27 01:51:48',
                'updated_at' => '2021-02-27 01:51:48',
            ),
            25 => 
            array (
                'id' => 36,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 2,
                'uuid' => '1a22558b-1324-4776-9cc8-29cd3f163925',
                'collection_name' => 'galleryPictureItems',
                'name' => 'KWU',
                'file_name' => 'KWU.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 6167,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Himatif Test","description":"Lorem ipsum dolor sit amet consectetur"}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 28,
                'created_at' => '2021-02-27 01:51:48',
                'updated_at' => '2021-02-27 01:51:48',
            ),
            26 => 
            array (
                'id' => 37,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 2,
                'uuid' => 'b9e13ba6-8f5e-451b-8f99-2ba25ffe584e',
                'collection_name' => 'galleryPictureItems',
                'name' => 'about-himatif',
                'file_name' => 'about-himatif.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 422687,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Himatif Test","description":"Lorem ipsum dolor sit amet consectetur"}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 28,
                'created_at' => '2021-02-27 01:51:48',
                'updated_at' => '2021-02-27 01:51:48',
            ),
            27 => 
            array (
                'id' => 38,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 2,
                'uuid' => '99ceecec-2afb-4a71-a6ee-4636f42f8b9c',
                'collection_name' => 'galleryPictureItems',
                'name' => 'Kerohanian',
                'file_name' => 'Kerohanian.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 7908,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Himatif Test","description":"Lorem ipsum dolor sit amet consectetur"}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 29,
                'created_at' => '2021-02-27 01:51:48',
                'updated_at' => '2021-02-27 01:51:48',
            ),
            28 => 
            array (
                'id' => 39,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 2,
                'uuid' => '313096b2-ba78-44be-b562-70e710e8b1b4',
                'collection_name' => 'galleryPictureItems',
                'name' => 'hero-img',
                'file_name' => 'hero-img.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 359724,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Himatif Test","description":"Lorem ipsum dolor sit amet consectetur"}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 30,
                'created_at' => '2021-02-27 01:51:48',
                'updated_at' => '2021-02-27 01:51:48',
            ),
            29 => 
            array (
                'id' => 40,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 2,
                'uuid' => 'a9a5e926-659e-4979-856f-c220e5f4ba9d',
                'collection_name' => 'galleryPictureItems',
                'name' => 'Minbak',
                'file_name' => 'Minbak.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 10366,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Himatif Test","description":"Lorem ipsum dolor sit amet consectetur"}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 31,
                'created_at' => '2021-02-27 01:51:48',
                'updated_at' => '2021-02-27 01:51:48',
            ),
            30 => 
            array (
                'id' => 41,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 2,
                'uuid' => '2ecb2c48-f0ab-420a-8c0a-cc0a4ae672c9',
                'collection_name' => 'galleryPictureItems',
                'name' => 'android-chrome-384x384',
                'file_name' => 'android-chrome-384x384.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 217207,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Himatif Test","description":"Lorem ipsum dolor sit amet consectetur"}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 32,
                'created_at' => '2021-02-27 01:51:48',
                'updated_at' => '2021-02-27 01:51:48',
            ),
            31 => 
            array (
                'id' => 42,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 2,
                'uuid' => '2dd7fe5e-018d-4f1d-ab56-d5fee8aaa854',
                'collection_name' => 'galleryPictureItems',
                'name' => 'foto-galeri',
                'file_name' => 'foto-galeri.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 245504,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Himatif Test","description":"Lorem ipsum dolor sit amet consectetur"}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 33,
                'created_at' => '2021-02-27 01:51:48',
                'updated_at' => '2021-02-27 01:51:48',
            ),
            32 => 
            array (
                'id' => 43,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 2,
                'uuid' => '9f102583-b99e-47ef-a08e-12bf12babd3a',
                'collection_name' => 'galleryPictureItems',
                'name' => 'favicon',
                'file_name' => 'favicon.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 232526,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Himatif Test","description":"Lorem ipsum dolor sit amet consectetur"}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 34,
                'created_at' => '2021-02-27 01:51:48',
                'updated_at' => '2021-02-27 01:51:48',
            ),
            33 => 
            array (
                'id' => 44,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 2,
                'uuid' => 'baddf7f0-df11-4a6e-8399-a0faef5f84f4',
                'collection_name' => 'galleryPictureItems',
                'name' => 'android-chrome-192x192',
                'file_name' => 'android-chrome-192x192.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 63683,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Himatif Test","description":"Lorem ipsum dolor sit amet consectetur"}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 35,
                'created_at' => '2021-02-27 01:51:48',
                'updated_at' => '2021-02-27 01:51:48',
            ),
            34 => 
            array (
                'id' => 45,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 2,
                'uuid' => 'ef23844d-5713-4018-88dc-5724a113ca22',
                'collection_name' => 'galleryPictureItems',
                'name' => 'IT',
                'file_name' => 'IT.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 5525,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Himatif Test","description":"Lorem ipsum dolor sit amet consectetur"}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 36,
                'created_at' => '2021-02-27 01:51:49',
                'updated_at' => '2021-02-27 01:51:49',
            ),
            35 => 
            array (
                'id' => 46,
                'model_type' => 'App\\Models\\Picture_gallery',
                'model_id' => 2,
                'uuid' => 'e74681eb-81c6-4ad5-943d-dcc28c3d0e45',
                'collection_name' => 'galleryPictureItems',
                'name' => 'apple-touch-icon',
                'file_name' => 'apple-touch-icon.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 56862,
                'manipulations' => '[]',
                'custom_properties' => '{"name":"Himatif Test","description":"Lorem ipsum dolor sit amet consectetur"}',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 37,
                'created_at' => '2021-02-27 01:51:49',
                'updated_at' => '2021-02-27 01:51:49',
            ),
        ));
        
        
    }
}